// Generated by gencpp from file robo/lidar.msg
// DO NOT EDIT!


#ifndef ROBO_MESSAGE_LIDAR_H
#define ROBO_MESSAGE_LIDAR_H

#include <ros/service_traits.h>


#include <robo/lidarRequest.h>
#include <robo/lidarResponse.h>


namespace robo
{

struct lidar
{

typedef lidarRequest Request;
typedef lidarResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lidar
} // namespace robo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robo::lidar > {
  static const char* value()
  {
    return "876c4429855d6020f9989528c5e136d4";
  }

  static const char* value(const ::robo::lidar&) { return value(); }
};

template<>
struct DataType< ::robo::lidar > {
  static const char* value()
  {
    return "robo/lidar";
  }

  static const char* value(const ::robo::lidar&) { return value(); }
};


// service_traits::MD5Sum< ::robo::lidarRequest> should match
// service_traits::MD5Sum< ::robo::lidar >
template<>
struct MD5Sum< ::robo::lidarRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robo::lidar >::value();
  }
  static const char* value(const ::robo::lidarRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo::lidarRequest> should match
// service_traits::DataType< ::robo::lidar >
template<>
struct DataType< ::robo::lidarRequest>
{
  static const char* value()
  {
    return DataType< ::robo::lidar >::value();
  }
  static const char* value(const ::robo::lidarRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robo::lidarResponse> should match
// service_traits::MD5Sum< ::robo::lidar >
template<>
struct MD5Sum< ::robo::lidarResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robo::lidar >::value();
  }
  static const char* value(const ::robo::lidarResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robo::lidarResponse> should match
// service_traits::DataType< ::robo::lidar >
template<>
struct DataType< ::robo::lidarResponse>
{
  static const char* value()
  {
    return DataType< ::robo::lidar >::value();
  }
  static const char* value(const ::robo::lidarResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBO_MESSAGE_LIDAR_H
